### PR TITLE
Add default titles and labels to issue templates.

### PR DESCRIPTION
**Pull request by Zimmi48**
See https://github.blog/changelog/2018-12-05-issue-template-automation-improvements

### CODE REVIEW

**Comment by Zimmi48** [comment]
GitHub's mouse-and-click update feature is buggy. I'll force-push a fix to this branch.

**Comment by Zimmi48** [comment]
Alright, here is a fixed version. This PR:

1. Renames the issue template files to order them differently.
2. Adds title templates to two of the three types of issues.
3. Adds default labels to all type of issues.

I have tested that it works at https://github.com/Zimmi48/manifesto.

If someone could additionally test over there if a PR submitter has the privilege to add a label (I don't think so), or remove a default label (this would be reasonable), then we could consider an additional tweak to the issue templates. For instance, we could add the label "maintainer-wanted" by default and suggest to issue authors to remove it. Although the main drawback of this approach is that most of the time, the label is not needed.

**Comment by erikmd** [comment]
> If someone could additionally test over there if a PR submitter has the privilege to add a label (I don't think so), or remove a default label (this would be reasonable),

I believe this is not possible: I had already noticed that external contributors (not members nor collaborators of the organization/repo) *do not have label editing permissions*.

Regarding the feature at stake (using an issue template from https://github.com/Zimmi48/manifesto) I noticed that:
* Even if the pre-selected label information and default title is gathered in the URL:
  https://github.com/Zimmi48/manifesto/issues/new?labels=move-project&template=1-move-a-project.md&title=Proposal+to+move+project+X+to+coq-community
* there is no drop-down list or so in the HTML page to remove/add such labels, cf. screenshot below.
* (But I did not test what would happen if the user modifies the URL and select, say, a label that does not exist… I can try it if you want :)

2019-08-09_18-44-55_Screenshot_Zimmi48_manifesto_3

**Comment by Zimmi48** [comment]
Can you try creating the issue? I'm now wondering if the default label feature will work at all for you given that you don't normally have the permission to set it. It would be a shame if it did not work.

**Comment by erikmd** [comment]
Hi @Zimmi48,

> Can you try creating the issue?

done.

To sum up, the default label mentioned in the template is always applied, even if the `?labels=…` parameter is changed to an existing (or non-existing) label. So, this looks sensible (and coherent with the initial assumption that external contributors can't interfere with labels editing).

**Comment by Zimmi48** [comment]
OK thanks! This is reasonable indeed. So I think this PR is good as-is.

**Comment by Zimmi48** [comment]
@erikmd I need a formal approval of someone else to merge this PR.

**Comment by anton-trunov** [comment]
Hi @Zimmi48! I happened to be around my laptop :)

**Pull request merged**
